#pragma config(Sensor, S1, leftTouchSensor, sensorEV3_Touch)
#pragma config(Sensor, S4, rightTouchSensor, sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LEFT_MOTOR motorA
#define RIGHT_MOTOR motorD
#define ROTATE 450
#define STRAIGHT 500
#define BACK 200
#define MAX_LENGTH 20
#define MOTER_POWER 50

#define FORWARD 0
#define TURNLEFT -1
#define TURNRIGHT 1

int stack = 0;

void turnR()
{
	motor[LEFT_MOTOR] = +MOTER_POWER;
	motor[RIGHT_MOTOR] = 0;
	wait1Msec(ROTATE);
}

void turnL()
{
	motor[LEFT_MOTOR] = 0;
	motor[RIGHT_MOTOR] = +MOTER_POWER;
	wait1Msec(ROTATE);
}

void goStraight()
{
	motor[LEFT_MOTOR] = +MOTER_POWER;
	motor[RIGHT_MOTOR] = +MOTER_POWER;
	wait1Msec(STRAIGHT);
}

void goBack()
{
	motor[LEFT_MOTOR] = -MOTER_POWER;
	motor[RIGHT_MOTOR] = -MOTER_POWER;
	wait1Msec(BACK);
}

void meetHurdle(int leftTouchValue, int rightTouchValue, int *dir, int *lastDir)
{

	if (leftTouchValue == 0 && rightTouchValue == 0)
	{
		goStraight();
	}
	else
	{
		if (*dir == FORWARD)
		{
			if (*lastDir == TURNLEFT)
			{
				goBack();
				turnL();
				*dir = TURNLEFT;
			}
			else if (*lastDir == TURNRIGHT)
			{
				goBack();
				turnR();
				*dir = TURNRIGHT;
			}
		}
		else if (*dir == TURNLEFT)
		{
			goBack();
			turnR();
			*dir = FORWARD;
			*lastDir = TURNRIGHT;
		}
		else if (*dir == TURNRIGHT)
		{
			goBack();
			turnL();
			*dir = FORWARD;
			*lastDir = TURNLEFT;
		}
	}
	stack++;
}

/*

dir lastDir moving
F   L       	f
L   L       	<
F   R       	f
R   R       	>
F   L      	    f

*/

task main()
{
	int dir = FORWARD;
	int lastDir = TURNLEFT;
	while (stack < 100)
	{
		meetHurdle(getTouchValue(leftTouchSensor), getTouchValue(rightTouchSensor), &dir, &lastDir);
	}
}
